on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
        -  mathcomp/mathcomp:2.0.0-coq-8.16
        -  mathcomp/mathcomp:2.1.0-coq-8.16
        -  mathcomp/mathcomp:2.0.0-coq-8.17
        -  mathcomp/mathcomp:2.1.0-coq-8.17
        -  mathcomp/mathcomp:2.0.0-coq-8.18
        -  mathcomp/mathcomp:2.1.0-coq-8.18
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: ${{ matrix.image }}
        before_install: |
          startGroup "Workaround permission issue"
            sudo chown -R coq:coq .
          endGroup
    - name: Revert permissions
      if: ${{ always() }}
      run: sudo chown -R 1001:116 .
